---
# 优先级：# specific_nodes > node_type (validator/sentry) > global
# 后面的配置会覆盖前面的配置

# 全局配置（所有节点）
global:
  config_toml:
    # 端口配置
    proxy_app: "tcp://127.0.0.1:26658"
    rpc.laddr: "tcp://127.0.0.1:26757"
    rpc.pprof_laddr: "localhost:6060"
    p2p.laddr: "tcp://0.0.0.0:26656"
    instrumentation.prometheus_listen_addr: ":26660"
    # 共识
    timeout_commit: "1.5s"
  
  app_toml:
    # 端口配置
    json-rpc.address:: "127.0.0.1:8545"
    json-rpc.ws-address:: "127.0.0.1:8546"
    api.address: "tcp://0.0.0.0:10337"
    grpc.address: "0.0.0.0:9900"
    # 
    minimum-gas-prices: "160000000inj"
    pruning: "default"
    min-retain-blocks: 10000

# 验证者节点配置（覆盖全局配置）
validator:
  config_toml:
    tx_index.indexer: "null"  # 共识节点禁用索引器
  
  app_toml:

# Sentry 节点配置（覆盖全局配置）
sentry:
  config_toml:
    tx_index.indexer: "kv"
  
  app_toml:

# 特定节点配置（覆盖类型配置）--> 归档节点
specific_nodes:
  validator-0:
    config_toml:

    app_toml:
      min-retain-blocks: 50000
  
  sentry-0:
    app_toml:
      pruning: "nothing"
      api-enable: true



